TasksTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: TasksTable-${self:provider.stage}
    AttributeDefinitions:
      - AttributeName: title
        AttributeType: S
    KeySchema:
      - AttributeName: title
        KeyType: HASH
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
